// Condensed BaoKim Risk mock data — adapted from the source codebase

const MOCK_RECORDS = [
  {
    stt: 1,
    id: "MRC-99482",
    timeOnboard: "2026-05-25 14:32",
    name: "CÔNG TY TNHH GIẢI PHÁP CÔNG NGHỆ MINH PHONG",
    shortName: "Minh Phong Tech",
    service: "Cổng thanh toán BaoKim",
    ccdvStatus: "KHONG_DUOC_CCDV",
    services: [
      { name: "Thu hộ / Chi hộ BaoKim" },
      { name: "Cổng thanh toán BaoKim" },
    ],
    blacklistStatus: "HIT",
    blacklistHits: ["Danh sách PEP", "Danh sách trốn thuế"],
    ruleHits: [
      "RULE_PEP_003: Trùng khớp họ tên và ngày sinh với PEP",
      "RULE_TAX_009: Mã số thuế liên đới doanh nghiệp nợ thuế"
    ],
    rrScore: 92,
    rrLevel: "CAO",
    source: "ERP",
    entityType: "TO_CHUC",
    mrcClass: "Master",
    personalInfo: {
      fullName: "Nguyễn Minh Phong",
      alias: "Phong Phong",
      dob: "15/08/1984",
      nationality: "Việt Nam",
      permanentAddress: "12 Láng Hạ, P. Thành Công, Q. Ba Đình, Hà Nội",
      currentAddress: "Vinhomes Metropolis, 29 Liễu Giai, Ba Đình, Hà Nội",
      country: "Việt Nam",
      idCardNo: "001084203920",
      citizenIdNo: "001084203920",
      passportNo: "B9281203",
      position: "Giám đốc điều hành (CEO)",
      phoneNumber: "0912 345 678",
    },
    businessInfo: {
      businessNameVN: "CÔNG TY TNHH GIẢI PHÁP CÔNG NGHỆ MINH PHONG",
      businessNameEN: "MINH PHONG TECHNOLOGY SOLUTIONS CO., LTD",
      shortName: "MINH PHONG TECH",
      businessLicenceNo: "0109283120",
      taxCode: "0109283120",
      headquarters: "Tầng 5, Tòa nhà Harec, 4A Láng Hạ, Ba Đình, Hà Nội",
      representative: "Nguyễn Minh Phong",
    },
    bankInfo: {
      accountNo: "19034820391023",
      bankName: "Techcombank",
      accountHolder: "CONG TY TNHH GP CN MINH PHONG",
    },
    businessType: "Công nghệ thông tin & Thương mại số",
    blacklistResults: [
      { name: "Danh sách PEP", match: "TRUNG_KHOP_TOAN_BO", action: "DUNG_CCDV", confidence: 98, version: "PEP_V4.9.2026_LIVE", reqId: "REQ-BK-99482-A01", fields: ["Họ tên", "Ngày sinh", "Quốc tịch"] },
      { name: "Danh sách trốn thuế", match: "TRUNG_KHOP_1_NHOM", action: "AP_DUNG_THEM_RULE", confidence: 72, version: "TAX_EVADERS_2026_Q2", reqId: "REQ-BK-99482-A02", fields: ["Mã số thuế", "Họ tên người đại diện"] },
      { name: "Danh sách đen nội bộ", match: "KHONG_TRUNG_KHOP", action: "TIEP_TUC_CCDV", confidence: 0, version: "BK_INTERNAL_BLACK_V9.2", reqId: "REQ-BK-99482-A03", fields: [] },
      { name: "Danh sách bị can, bị cáo", match: "KHONG_TRUNG_KHOP", action: "TIEP_TUC_CCDV", confidence: 0, version: "MPS_CONVICTED_DAILY_2026", reqId: "REQ-BK-99482-A04", fields: [] },
      { name: "Danh sách cảnh báo CIC", match: "KHONG_TRUNG_KHOP", action: "TIEP_TUC_CCDV", confidence: 0, version: "CIC_CREDIT_ALERTS_V1.0", reqId: "REQ-BK-99482-A05", fields: [] },
      { name: "Danh sách SIMO", match: "KHONG_TRUNG_KHOP", action: "TIEP_TUC_CCDV", confidence: 0, version: "SIMO_VOIP_SHADOW_V3.8", reqId: "REQ-BK-99482-A06", fields: [] },
    ],
    screeningHistory: [
      { runId: "RUN-20260510-0900", timestamp: "2026-05-10 09:00", actor: "Hệ thống Risk (Quét định kỳ)", reason: "Rà soát định kỳ", rrScore: 45, rrLevel: "TRUNG_BINH", blacklistStatus: "HIT", ccdvStatus: "DUOC_CCDV", hits: ["Danh sách trốn thuế"] },
      { runId: "RUN-20260318-1432", timestamp: "2026-03-18 14:32", actor: "Hệ thống Risk (Quét định kỳ)", reason: "Rà soát định kỳ", rrScore: 28, rrLevel: "THAP", blacklistStatus: "KHONG_HIT", ccdvStatus: "DUOC_CCDV", hits: [] },
    ],
  },
  {
    stt: 2,
    id: "MRC-99120",
    timeOnboard: "2026-05-25 11:20",
    name: "HỘ KINH DOANH NGUYỄN VĂN HÙNG",
    shortName: "HKD Nguyễn Văn Hùng",
    service: "Thu hộ / Chi hộ BaoKim",
    ccdvStatus: "DUOC_CCDV",
    services: [
      { name: "Thu hộ / Chi hộ BaoKim" },
    ],
    blacklistStatus: "KHONG_HIT",
    blacklistHits: [],
    ruleHits: [],
    rrScore: 8,
    rrLevel: "THAP",
    source: "PORTAL_B2B",
    entityType: "HO_KINH_DOANH",
    mrcClass: "Direct",
    personalInfo: {
      fullName: "Nguyễn Văn Hùng",
      alias: "Hùng Béo",
      dob: "12/05/1990",
      nationality: "Việt Nam",
      permanentAddress: "Khối 5, TT. Đô Lương, H. Đô Lương, Nghệ An",
      currentAddress: "45 Ngõ 192 Lê Trọng Tấn, Thanh Xuân, Hà Nội",
      country: "Việt Nam",
      idCardNo: "036090012345",
      citizenIdNo: "036090012345",
      passportNo: "—",
      position: "Chủ hộ kinh doanh",
      phoneNumber: "0987 654 321",
    },
    businessInfo: {
      businessNameVN: "HỘ KINH DOANH NGUYỄN VĂN HÙNG",
      businessNameEN: "—",
      shortName: "HKD HÙNG",
      businessLicenceNo: "8001029301",
      taxCode: "8001029301",
      headquarters: "45 Ngõ 192 Lê Trọng Tấn, Thanh Xuân, Hà Nội",
      representative: "Nguyễn Văn Hùng",
    },
    bankInfo: {
      accountNo: "1010 0123 4567",
      bankName: "Vietcombank",
      accountHolder: "NGUYEN VAN HUNG",
    },
    businessType: "Kinh doanh tạp hóa & dịch vụ thanh toán",
    blacklistResults: [
      { name: "Danh sách PEP", match: "KHONG_TRUNG_KHOP", action: "TIEP_TUC_CCDV", confidence: 0, version: "PEP_V4.9.2026_LIVE", reqId: "REQ-BK-99120-01", fields: [] },
      { name: "Danh sách trốn thuế", match: "KHONG_TRUNG_KHOP", action: "TIEP_TUC_CCDV", confidence: 0, version: "TAX_EVADERS_2026_Q2", reqId: "REQ-BK-99120-02", fields: [] },
      { name: "Danh sách đen nội bộ", match: "KHONG_TRUNG_KHOP", action: "TIEP_TUC_CCDV", confidence: 0, version: "BK_INTERNAL_BLACK_V9.2", reqId: "REQ-BK-99120-03", fields: [] },
      { name: "Danh sách bị can, bị cáo", match: "KHONG_TRUNG_KHOP", action: "TIEP_TUC_CCDV", confidence: 0, version: "MPS_CONVICTED_DAILY_2026", reqId: "REQ-BK-99120-04", fields: [] },
    ],
    screeningHistory: [
      { runId: "RUN-20260501-0900", timestamp: "2026-05-01 09:00", actor: "Hệ thống tự động", reason: "Rà soát định kỳ", rrScore: 8, rrLevel: "THAP", blacklistStatus: "KHONG_HIT", ccdvStatus: "DUOC_CCDV", hits: [] },
    ],
  },
  {
    stt: 3,
    id: "MRC-98711",
    timeOnboard: "2026-05-25 09:15",
    name: "CÔNG TY CỔ PHẦN BÁN LẺ AN BÌNH",
    shortName: "An Bình Retail",
    service: "Tài khoản định danh ảo (VA)",
    ccdvStatus: "DUOC_CCDV",
    services: [
      { name: "Tài khoản định danh ảo (VA)" },
      { name: "Thu hộ / Chi hộ BaoKim" },
    ],
    blacklistStatus: "KHONG_HIT",
    blacklistHits: [],
    ruleHits: ["RULE_KYC_021: Cảnh báo địa chỉ trụ sở thuê chung"],
    rrScore: 34,
    rrLevel: "TRUNG_BINH",
    source: "PORTAL_B2B",
    entityType: "TO_CHUC",
    mrcClass: "Direct",
    personalInfo: {
      fullName: "Trần Thị Bình",
      alias: "—",
      dob: "22/11/1981",
      nationality: "Việt Nam",
      permanentAddress: "Số 88, đường Nguyễn Văn Cừ, Long Biên, Hà Nội",
      currentAddress: "Số 88, đường Nguyễn Văn Cừ, Long Biên, Hà Nội",
      country: "Việt Nam",
      idCardNo: "001181029384",
      citizenIdNo: "001181029384",
      passportNo: "C2810392",
      position: "Chủ tịch HĐQT",
      phoneNumber: "0903 281 920",
    },
    businessInfo: {
      businessNameVN: "CÔNG TY CỔ PHẦN BÁN LẺ AN BÌNH",
      businessNameEN: "AN BINH RETAIL JSC.",
      shortName: "AN BÌNH RETAIL",
      businessLicenceNo: "0312842091",
      taxCode: "0312842091",
      headquarters: "Tầng 12, Tòa nhà Mipec Riverside, Long Biên, Hà Nội",
      representative: "Trần Thị Bình",
    },
    bankInfo: {
      accountNo: "0091 2884 7263",
      bankName: "MB Bank",
      accountHolder: "CONG TY CO PHAN AN BINH",
    },
    businessType: "Bán lẻ hàng tiêu dùng & FMCG",
    blacklistResults: [
      { name: "Danh sách PEP", match: "KHONG_TRUNG_KHOP", action: "TIEP_TUC_CCDV", confidence: 0, version: "PEP_V4.9.2026_LIVE", reqId: "REQ-BK-98711-01", fields: [] },
      { name: "Danh sách trốn thuế", match: "KHONG_TRUNG_KHOP", action: "TIEP_TUC_CCDV", confidence: 0, version: "TAX_EVADERS_2026_Q2", reqId: "REQ-BK-98711-02", fields: [] },
      { name: "Danh sách đen nội bộ", match: "KHONG_TRUNG_KHOP", action: "AP_DUNG_THEM_RULE", confidence: 18, version: "BK_INTERNAL_BLACK_V9.2", reqId: "REQ-BK-98711-03", fields: ["Địa chỉ trụ sở"] },
    ],
    screeningHistory: [],
  },
  {
    stt: 4,
    id: "MRC-98640",
    timeOnboard: "2026-05-24 17:48",
    name: "CÔNG TY TNHH THƯƠNG MẠI HOÀNG LONG",
    shortName: "Hoàng Long Trading",
    service: "Cổng thanh toán BaoKim",
    ccdvStatus: "KHONG_DUOC_CCDV",
    services: [
      { name: "Cổng thanh toán BaoKim" },
      { name: "Tài khoản định danh ảo (VA)" },
    ],
    blacklistStatus: "HIT",
    blacklistHits: ["Danh sách đen nội bộ"],
    ruleHits: ["RULE_FRAUD_014: Lịch sử chargeback lặp lại trên 3 lần"],
    rrScore: 85,
    rrLevel: "CAO",
    source: "PORTAL_B2B",
    entityType: "TO_CHUC",
    mrcClass: "Direct",
    personalInfo: {
      fullName: "Phạm Hoàng Long",
      alias: "Long Bốn Mắt",
      dob: "04/07/1978",
      nationality: "Việt Nam",
      permanentAddress: "Số 9, đường Phạm Văn Đồng, Cầu Giấy, Hà Nội",
      currentAddress: "Số 9, đường Phạm Văn Đồng, Cầu Giấy, Hà Nội",
      country: "Việt Nam",
      idCardNo: "001078201938",
      citizenIdNo: "001078201938",
      passportNo: "B4029182",
      position: "Giám đốc",
      phoneNumber: "0978 102 384",
    },
    businessInfo: {
      businessNameVN: "CÔNG TY TNHH THƯƠNG MẠI HOÀNG LONG",
      businessNameEN: "HOANG LONG TRADING CO., LTD",
      shortName: "HOÀNG LONG",
      businessLicenceNo: "0109385721",
      taxCode: "0109385721",
      headquarters: "Số 9, Phạm Văn Đồng, Cầu Giấy, Hà Nội",
      representative: "Phạm Hoàng Long",
    },
    bankInfo: {
      accountNo: "1102 0093 8472",
      bankName: "BIDV",
      accountHolder: "CONG TY TNHH TM HOANG LONG",
    },
    businessType: "Thương mại điện tử xuyên biên giới",
    blacklistResults: [
      { name: "Danh sách PEP", match: "KHONG_TRUNG_KHOP", action: "TIEP_TUC_CCDV", confidence: 0, version: "PEP_V4.9.2026_LIVE", reqId: "REQ-BK-98640-01", fields: [] },
      { name: "Danh sách đen nội bộ", match: "TRUNG_KHOP_TOAN_BO", action: "DUNG_CCDV", confidence: 100, version: "BK_INTERNAL_BLACK_V9.2", reqId: "REQ-BK-98640-02", fields: ["MST", "Mã merchant cũ"] },
    ],
    screeningHistory: [
      { runId: "RUN-20260201-1100", timestamp: "2026-02-01 11:00", actor: "Hệ thống Risk", reason: "Rà soát định kỳ", rrScore: 60, rrLevel: "TRUNG_BINH", blacklistStatus: "KHONG_HIT", ccdvStatus: "DUOC_CCDV", hits: [] },
    ],
  },
  {
    stt: 5,
    id: "MRC-98552",
    timeOnboard: "2026-05-24 14:02",
    name: "NGUYỄN THỊ LAN ANH",
    shortName: "Cá nhân — Lan Anh",
    service: "Ví điện tử BaoKim",
    ccdvStatus: "DUOC_CCDV",
    services: [
      { name: "Ví điện tử BaoKim" },
    ],
    blacklistStatus: "KHONG_HIT",
    blacklistHits: [],
    ruleHits: [],
    rrScore: 5,
    rrLevel: "THAP",
    source: "DV_KHAC",
    entityType: "CA_NHAN",
    mrcClass: "Sub",
    personalInfo: {
      fullName: "Nguyễn Thị Lan Anh",
      alias: "—",
      dob: "30/03/1995",
      nationality: "Việt Nam",
      permanentAddress: "Số 22, đường Trần Phú, Hà Đông, Hà Nội",
      currentAddress: "Số 22, đường Trần Phú, Hà Đông, Hà Nội",
      country: "Việt Nam",
      idCardNo: "030195013820",
      citizenIdNo: "030195013820",
      passportNo: "—",
      position: "Cá nhân",
      phoneNumber: "0912 884 002",
    },
    businessInfo: { businessNameVN: "—", businessNameEN: "—", shortName: "—", businessLicenceNo: "—", taxCode: "—", headquarters: "—", representative: "—" },
    bankInfo: { accountNo: "0203 9281 7263", bankName: "VPBank", accountHolder: "NGUYEN THI LAN ANH" },
    businessType: "Cá nhân — sử dụng ví",
    blacklistResults: [
      { name: "Danh sách PEP", match: "KHONG_TRUNG_KHOP", action: "TIEP_TUC_CCDV", confidence: 0, version: "PEP_V4.9.2026_LIVE", reqId: "REQ-BK-98552-01", fields: [] },
      { name: "Danh sách SIMO", match: "KHONG_TRUNG_KHOP", action: "TIEP_TUC_CCDV", confidence: 0, version: "SIMO_VOIP_SHADOW_V3.8", reqId: "REQ-BK-98552-02", fields: [] },
    ],
    screeningHistory: [],
  },
  {
    stt: 6,
    id: "MRC-98401",
    timeOnboard: "2026-05-24 10:30",
    name: "CÔNG TY CỔ PHẦN GIÁO DỤC EDUTECH VIỆT",
    shortName: "Edutech Việt",
    service: "Thu hộ / Chi hộ BaoKim",
    ccdvStatus: "DUOC_CCDV",
    services: [
      { name: "Thu hộ / Chi hộ BaoKim" },
      { name: "Cổng thanh toán BaoKim" },
      { name: "Tài khoản định danh ảo (VA)" },
    ],
    blacklistStatus: "KHONG_HIT",
    blacklistHits: [],
    ruleHits: [],
    rrScore: 12,
    rrLevel: "THAP",
    source: "PORTAL_B2B",
    entityType: "TO_CHUC",
    mrcClass: "Master",
    personalInfo: {
      fullName: "Lê Văn Khôi",
      alias: "—",
      dob: "18/02/1986",
      nationality: "Việt Nam",
      permanentAddress: "Số 5, Khu đô thị Văn Phú, Hà Đông, Hà Nội",
      currentAddress: "Số 5, Khu đô thị Văn Phú, Hà Đông, Hà Nội",
      country: "Việt Nam",
      idCardNo: "001086019283",
      citizenIdNo: "001086019283",
      passportNo: "—",
      position: "Tổng Giám đốc",
      phoneNumber: "0901 824 738",
    },
    businessInfo: {
      businessNameVN: "CÔNG TY CỔ PHẦN GIÁO DỤC EDUTECH VIỆT",
      businessNameEN: "EDUTECH VIET JSC.",
      shortName: "EDUTECH VIỆT",
      businessLicenceNo: "0108374829",
      taxCode: "0108374829",
      headquarters: "Tòa nhà CT4, KĐT Văn Phú, Hà Đông, Hà Nội",
      representative: "Lê Văn Khôi",
    },
    bankInfo: { accountNo: "1100 3829 0182", bankName: "Vietcombank", accountHolder: "CTY CP GD EDUTECH VIET" },
    businessType: "Giáo dục trực tuyến & nội dung số",
    blacklistResults: [
      { name: "Danh sách PEP", match: "KHONG_TRUNG_KHOP", action: "TIEP_TUC_CCDV", confidence: 0, version: "PEP_V4.9.2026_LIVE", reqId: "REQ-BK-98401-01", fields: [] },
      { name: "Danh sách trốn thuế", match: "KHONG_TRUNG_KHOP", action: "TIEP_TUC_CCDV", confidence: 0, version: "TAX_EVADERS_2026_Q2", reqId: "REQ-BK-98401-02", fields: [] },
    ],
    screeningHistory: [
      { runId: "RUN-20260424-1030", timestamp: "2026-04-24 10:30", actor: "Hệ thống tự động", reason: "Rà soát định kỳ", rrScore: 14, rrLevel: "THAP", blacklistStatus: "KHONG_HIT", ccdvStatus: "DUOC_CCDV", hits: [] },
    ],
  },
  {
    stt: 7,
    id: "MRC-98123",
    timeOnboard: "2026-05-23 16:55",
    name: "CÔNG TY TNHH TƯ VẤN ĐẦU TƯ LẠC HỒNG",
    shortName: "Lạc Hồng Invest",
    service: "Cổng thanh toán BaoKim",
    ccdvStatus: "DUOC_CCDV",
    services: [
      { name: "Cổng thanh toán BaoKim" },
      { name: "Thu hộ / Chi hộ BaoKim" },
    ],
    blacklistStatus: "HIT",
    blacklistHits: ["Danh sách cảnh báo CIC"],
    ruleHits: ["RULE_CIC_018: Doanh nghiệp có dư nợ nhóm 3 tại tổ chức tín dụng"],
    rrScore: 58,
    rrLevel: "TRUNG_BINH",
    source: "ERP",
    entityType: "TO_CHUC",
    mrcClass: "Direct",
    personalInfo: {
      fullName: "Đặng Quốc Việt",
      alias: "—",
      dob: "09/09/1975",
      nationality: "Việt Nam",
      permanentAddress: "Số 19, đường Lê Đại Hành, Hai Bà Trưng, Hà Nội",
      currentAddress: "Số 19, đường Lê Đại Hành, Hai Bà Trưng, Hà Nội",
      country: "Việt Nam",
      idCardNo: "001075203847",
      citizenIdNo: "001075203847",
      passportNo: "B8273645",
      position: "Giám đốc",
      phoneNumber: "0918 273 645",
    },
    businessInfo: {
      businessNameVN: "CÔNG TY TNHH TƯ VẤN ĐẦU TƯ LẠC HỒNG",
      businessNameEN: "LAC HONG INVESTMENT CONSULTING CO., LTD",
      shortName: "LẠC HỒNG INVEST",
      businessLicenceNo: "0107382910",
      taxCode: "0107382910",
      headquarters: "Số 19, Lê Đại Hành, Hai Bà Trưng, Hà Nội",
      representative: "Đặng Quốc Việt",
    },
    bankInfo: { accountNo: "0301 9283 7261", bankName: "Sacombank", accountHolder: "CTY TNHH TVDT LAC HONG" },
    businessType: "Tư vấn tài chính & đầu tư",
    blacklistResults: [
      { name: "Danh sách cảnh báo CIC", match: "TRUNG_KHOP_1_NHOM", action: "AP_DUNG_THEM_RULE", confidence: 65, version: "CIC_CREDIT_ALERTS_V1.0", reqId: "REQ-BK-98123-01", fields: ["Mã số thuế"] },
    ],
    screeningHistory: [
      { runId: "RUN-20260423-1655", timestamp: "2026-04-23 16:55", actor: "Hệ thống Risk", reason: "Rà soát định kỳ", rrScore: 42, rrLevel: "TRUNG_BINH", blacklistStatus: "KHONG_HIT", ccdvStatus: "DUOC_CCDV", hits: [] },
    ],
  },
  {
    stt: 8,
    id: "MRC-98014",
    timeOnboard: "2026-05-23 09:20",
    name: "HỘ KINH DOANH PHẠM THỊ MỸ DUYÊN",
    shortName: "HKD Mỹ Duyên",
    service: "Tài khoản định danh ảo (VA)",
    ccdvStatus: "DUOC_CCDV",
    services: [
      { name: "Tài khoản định danh ảo (VA)" },
    ],
    blacklistStatus: "KHONG_HIT",
    blacklistHits: [],
    ruleHits: [],
    rrScore: 15,
    rrLevel: "THAP",
    source: "PORTAL_B2B",
    entityType: "HO_KINH_DOANH",
    mrcClass: "Sub",
    personalInfo: {
      fullName: "Phạm Thị Mỹ Duyên",
      alias: "—",
      dob: "21/12/1988",
      nationality: "Việt Nam",
      permanentAddress: "Số 78, đường Nguyễn Trãi, TP. Vinh, Nghệ An",
      currentAddress: "Số 78, đường Nguyễn Trãi, TP. Vinh, Nghệ An",
      country: "Việt Nam",
      idCardNo: "040088012394",
      citizenIdNo: "040088012394",
      passportNo: "—",
      position: "Chủ hộ kinh doanh",
      phoneNumber: "0944 829 102",
    },
    businessInfo: {
      businessNameVN: "HỘ KINH DOANH PHẠM THỊ MỸ DUYÊN",
      businessNameEN: "—",
      shortName: "HKD MỸ DUYÊN",
      businessLicenceNo: "8003827191",
      taxCode: "8003827191",
      headquarters: "Số 78, đường Nguyễn Trãi, TP. Vinh, Nghệ An",
      representative: "Phạm Thị Mỹ Duyên",
    },
    bankInfo: { accountNo: "0203 8472 1029", bankName: "Agribank", accountHolder: "PHAM THI MY DUYEN" },
    businessType: "Nhà hàng & dịch vụ ăn uống",
    blacklistResults: [
      { name: "Danh sách PEP", match: "KHONG_TRUNG_KHOP", action: "TIEP_TUC_CCDV", confidence: 0, version: "PEP_V4.9.2026_LIVE", reqId: "REQ-BK-98014-01", fields: [] },
    ],
    screeningHistory: [],
  },
];

const SERVICES_LIST = [
  "Cổng thanh toán BaoKim",
  "Thu hộ / Chi hộ BaoKim",
  "Tài khoản định danh ảo (VA)",
  "Ví điện tử BaoKim",
];

const BLACKLIST_GROUPS = [
  "Danh sách PEP",
  "Danh sách trốn thuế",
  "Danh sách đen nội bộ",
  "Danh sách bị can, bị cáo",
  "Danh sách cảnh báo CIC",
  "Danh sách SIMO",
];

window.MOCK_RECORDS = MOCK_RECORDS;
window.SERVICES_LIST = SERVICES_LIST;
window.BLACKLIST_GROUPS = BLACKLIST_GROUPS;
